char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - LeftShoulder
  - LeftElbow
  - LeftWrist
  - LFingers
  - RightShoulder
  - RightElbow
  - RightWrist
  - RFingers
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - LeftHip
  - LeftKnee
  - LeftAnkle
  - LeftToe
  - RightHip
  - RightKnee
  - RightAnkle
  - RightToe
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Chest
  - Chest2
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftWrist
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightWrist
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftAnkle
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightAnkle
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightAnkle
    - RightKnee
    - RightHip
  - - LeftAnkle
    - LeftKnee
    - LeftHip
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftShoulder
  - LeftElbow
  left_foot: !!python/tuple
  - LeftKnee
  - LeftAnkle
  left_hand: !!python/tuple
  - LeftElbow
  - LeftWrist
  left_knee: !!python/tuple
  - LeftHip
  - LeftKnee
  torso: !!python/tuple
  - Hips
  - Chest2
  neck: !!python/tuple
  - Hips
  - Head
  right_elbow: !!python/tuple
  - RightShoulder
  - RightElbow
  right_foot: !!python/tuple
  - RightKnee
  - RightAnkle
  right_hand: !!python/tuple
  - RightElbow
  - RightWrist
  right_knee: !!python/tuple
  - RightHip
  - RightKnee
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder