filepath: examples/bvh/fair1/jumping.bvh
start_frame_idx: 150
end_frame_idx: 654 
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +z
