scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char3/char_cfg.yaml
      motion_cfg: examples/config/motion/jumping_jacks.yaml
      retarget_cfg: examples/config/retarget/cmu1_pfp.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif