scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/char5/char_cfg.yaml
      motion_cfg: examples/config/motion/dab.yaml
      retarget_cfg: examples/config/retarget/six_arms.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif