name: Android CI

on:
  pull_request:
    branches: [ "develop_front" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
        echo "${{ secrets.LOCAL_PROPERTIES }}" >> local.properties

    - name: Create google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
